export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_RESET = 'SIGNIN_RESET';
export const SIGNIN_SESSION = 'SIGNIN_SESSION';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_RESET = 'SIGNUP_RESET';

export const FRIENDS_START = 'FRIENDS_START';
export const FRIENDS_SUCCESS = 'FRIENDS_SUCCESS';
export const FRIENDS_FAIL = 'FRIENDS_FAIL';
